logging.level: debug
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /logs/app.log
  json.keys_under_root: true
  json.overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]